name: ikonfete
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter: ^0.3.4
  firebase_auth: ^0.8.1+4
  firebase_database: ^2.0.2
  firebase_storage: ^2.1.0+1
  cloud_firestore: ^0.9.7
  cloud_functions: ^0.1.2
  shared_preferences: ^0.5.1+1
  flutter_facebook_login: ^2.0.0
  flutter_twitter_login: ^1.1.0
  http: ^0.12.0+1
  rxdart: ^0.20.0
  progress_indicators: ^0.1.2
  fluro: ^1.4.0
  image: ^2.0.7
  image_picker: ^0.5.0+6
  flutter_svg: ^0.12.0
  transparent_image: ^1.0.0
  cached_network_image: ^0.7.0
  mime: ^0.9.6+2
  country_pickers: ^1.0.1
  flutter_bloc: ^0.7.1
  timeago: ^2.0.10
  photo_view: ^0.2.2
  chewie: ^0.9.6
  path_provider: ^0.5.0+1
  flutter_swiper: ^1.1.5
  flutter_simple_dependency_injection: ^1.0.1
  equatable: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
  - assets/images/splash_background.png
  - assets/images/Ikonfete_logo_white.png
  - assets/images/onboard_background1.png
  - assets/images/onboard_background2.png
  - assets/images/onboard_background3.png
  - assets/images/onboard_background4.png
  - assets/images/alert.svg
  - assets/images/dark_grunge_bk.jpg
  - assets/images/deezer.png
  - assets/deezer/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
  - family: Themify
    fonts:
    - asset: assets/fonts/themify.ttf
  - family: FontAwesome5
    fonts:
    - asset: assets/fonts/fa-regular-400.ttf
  - family: FontAwesome5Solid
    fonts:
    - asset: assets/fonts/fa-solid-900.ttf
  - family: FontAwesome5Brands
    fonts:
    - asset: assets/fonts/fa-brands-400.ttf
  - family: LineAwesome
    fonts:
    - asset: assets/fonts/line-awesome.ttf
  - family: Bebas
    fonts:
    - asset: assets/fonts/bebas.ttf
  - family: SanFranciscoDisplay
    fonts:
    - asset: assets/fonts/sanfranciscodisplay-medium.ttf
    - asset: assets/fonts/sanfranciscodisplay-semibold.ttf
      weight: 500
    - asset: assets/fonts/sanfranciscodisplay-bold.ttf
      weight: 900
  - family: mermaid
    fonts:
    - asset: assets/fonts/Mermaid1001.ttf
  - family: bebas-neue
    fonts:
    - asset: assets/fonts/BebasNeue-Regular.ttf
